# Generated by Django 3.2.8 on 2021-10-08 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_myphoto_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myphoto',
            old_name='Category',
            new_name='category',
        ),
    ]
